# -*- coding: utf-8 -*-
"""anvil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSOhBnJ3NrEr6cgXwQfyiTaC8WXJ8aLD
"""

!pip install anvil-uplink

import anvil.server

anvil.server.connect("server_PDY3TCGIOLWIA4NZNPOHZ2S2-T4GOSMIVHIW7CS2X")

@anvil.server.callable
def say_hello(name):
 return "Hello" + name

from google.colab import drive
drive.mount('/content/drive')

# load and evaluate a saved model
from numpy import loadtxt
from tensorflow.keras.models import load_model

# load model
model = load_model('/content/drive/MyDrive/vgg_model.h5')
# summarize model.
model.summary()

import requests
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

url =" "
r= requests.get(url,stream= True)

def prediksi(img):
  img = cv2.resize(img, (224,224))
  img_array = np.array(img)
  img_array = np.expand_dims(img_array,axis=0)
  img_array = preprocess_input(img_array)
  pred = model.predict(img_array)
  class_idx = np.argmax(pred , axis=1)[0]
  class_names = ['horse','elephant','chicken','cat','cow']
  class_name = class_names[class_idx]
  print('The predicted class is:' , class_name)
  return(class_name)
prediksi(img)



prediksi(img)

import anvil.media

@anvil.server.callable
def classify_image(file):
  with anvil.media.TempFile(file) as f:
    img = np.array(Image.open(f))
   
  hasil = prediksi(img)
  print(hasil)
  return(hasil)

anvil.server.wait_forever()

